Fix: Use keyword arguments with Pydispatcher.send
This proposed patch:

1. Uses keyword arguments
2. Drops the "sender" argument from `dispatcher.send` calls
3. Drops the "sender" keyword from event handlers

# Rationale

Pydispatcher has some byzantine logic when dealing with positional arguments.

- `send`ind positional argument requires specifying the`sender` argument
- Recieving positional arguments requires positional-only arguments

Incorrect:

```py
def func(sender, choices)
    ...

dispatcher.connect("event", func)

dispatcher.send("event", None, "some choice")
# => TypeError: Argument 'sender' specified both positionally and as a keyword for calling <bound method View.show_choices of <engine.view.View object at 0x7f86c904a660>

dispatcher.send("event", "some choice")
# => TypeError: View.show_choices() missing 1 required positional argument: 'choices'
```

## Solution 1: Use keyword arguments

```py
class A:
    def func(self, sender, choices)
        ...

dispatcher.connect("event", func)

dispatcher.send("event", choices="some choices")
# => This runs!
```

## Solution 2: Use positional-only arguments in handlers

```py
def func(choices, \ sender)
    ...

dispatcher.connect("event", func)

dispatcher.send("event", None, "some choice")
# => This runs!

# But we still need to specify the sender:
dispatcher.send("event", "some choice")
# => TypeError: View.show_choices() missing 1 required positional argument: 'choices'
```

## Proposed Solution:

1. Use keyword arguments, since they're simpler

2. Drop the "sender" argument from `send` calls
    - This internally defaults to the "Anynymous" sender

3. Drop the "sender" keyword from handlers
    - pydispatch only sends the required keywords