Sidebar: Add debug tracing to the Parser
This change adds simple parser logging, to make it easy to see why the parser fails.

This might need to be split off as its own PR, since the solution is messy.

## Example: Debugging the Goto node

Problem: I wrote a `Goto` node, but it was not recognize the map! I had no idea why!

Solution: But the log clearly indicates the problem: `Goto` is not a candidate node! I forgot to add it to  the syntax!

```
$ pytest -k simple_goto.yaml
....
....
DEBUG    Parser:parser.py:37 Parsing None node with: {'print': 'Arrived at sibling_block.\n'}
DEBUG    Parser:parser.py:124 => Parse as map. Candidate nodes: ['If', 'A', 'Doc', 'Block', 'Choice', 'Print', 'Error']:
DEBUG    Parser:parser.py:130 ===> Matched tags for Print.
DEBUG    Parser:parser.py:37 Parsing Expression node with: Arrived at sibling_block.
DEBUG    Parser:parser.py:37 Parsing None node with: {'goto': '/start/child_block'}
DEBUG    Parser:parser.py:124 => Parse as map. Candidate nodes: ['If', 'A', 'Doc', 'Block', 'Choice', 'Print', 'Error']:

Short test summary info:
FAILED tests/test_stories.py::test_story[simple_goto.yaml] - engine.exceptions.NotRecognized: Unrecognized map: {'goto': '/start/child_block'}
```